name: generic-app
apiVersion: v2
version: 1.3.0
appVersion: 1.0.0
description: Helm chart for generic apps by sberg it-systeme GmbH
home: https://www.sberg.net
keywords:
  - generic
  - sberg
  - kubernetes
maintainers:
  - name: sberg it-systeme GmbH
    url: https://github.com/sberg-net/helm/tree/main/charts
annotations:
  category: Infrastructure
  licenses: Apache-2.0
dependencies:
  - name: mariadb
    version: 0.14.1
    repository: oci://registry-1.docker.io/cloudpirates
    condition: mariadb.enabled
  - name: common
    version: 2.x.x
    repository: oci://registry-1.docker.io/bitnamicharts
    tags:
      - bitnami-common
