name: test-app

privateRegistry:
  name: gitlab-registry.sberg.net
  imagePullSecret:
    username: stephan
    token: glpat-CnssVgAvYokCAgERHW_D

app:
  image:
    version: 3.7.2
    repository: gitlab-registry.sberg.net/ti/eldix4kim/eldix4kim-springboot
  nodeSelector:
    kubernetes.io/arch: arm64
  dynamicParameter:
    - name: LOGGER_LEVEL_NET_SBERG
      value: debug
  securityContext:
    runAsUser: 1001
    runAsGroup: 1001
    fsGroup: 1001
  startupProbe:
    enabled: false
  service:
    web:
      port: 80
      type: ClusterIP

externalDatabase:
  enabled: false
  hostname: mariadb-external.sberg-devel.svc.cluster.local
  database: eldix
  username: extern
  password: mrdata
