{{ if and .Values.privateRegistry.imagePullSecret.name .Values.privateRegistry.imagePullSecret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.privateRegistry.imagePullSecret.name }}
  labels:
    app.kubernetes.io/name: {{ template "app.name" . }}
    helm.sh/chart: {{ include "app.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}
