apiVersion: v1
kind: Service
metadata:
  name: "{{ template "app.fullname" . }}-web"
  labels:
    app.kubernetes.io/name: {{ template "app.name" . }}
    helm.sh/chart: {{ include "app.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  ports:
    - name: "{{ template "app.fullname" . }}-web"
      port: {{ default 80 .Values.app.service.web.port }}
      protocol: TCP
      targetPort: 8080
  selector:
    app: "{{ template "app.fullname" . }}"
  type: "{{ default "ClusterIP" .Values.app.service.web.type }}"
